using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DocNetPress.Development.Generator
{
    /// <summary>
    /// Enum giving the type of the post
    /// </summary>
    public enum PostType
    {
        /// <summary>
        /// The posts generated by the <see cref="DocNetPress.Development.Generator.PostGenerator"/> are WordPress pages
        /// </summary>
        Page,

        /// <summary>
        /// The posts generated by the <see cref="DocNetPress.Development.Generator.PostGenerator"/> are WordPress posts
        /// </summary>
        Post,

        /// <summary>
        /// The post generated by the <see cref="DocNetPress.Development.Generator.PostGenerator"/> will be a custom taxonomy type
        /// </summary>
        Custom
    }
}
