using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DocNetPress.Generators
{
    /// <summary>
    /// Enum giving the type of the post
    /// </summary>
    public enum PostType
    {
        /// <summary>
        /// The posts generated by the <see cref="DocNetPress.Generators.PageGenerator"/> are WordPress pages
        /// </summary>
        Page,

        /// <summary>
        /// The posts generated by the <see cref="DocNetPress.Generators.PageGenerator"/> are WordPress posts
        /// </summary>
        Post
    }
}
